### Create User
POST http://localhost:3000/users/signup
content-type: application/json

{
    "email": "asdf@sparta.com",
    "name": "asdf",
    "number": ["010-1234-1234"],
    "accessKey": "asdf",
    "serviceId": "asdf"
}

### login
Post http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "sdf@sparta.com"
}

### update User-info
Patch http://localhost:3000/users/1
Content-Type: application/json

{
    "accessKey": "asd133",
    "serviceId": "asd313",
    "email": "asd@sparta.com"
}