### Create User
POST http://localhost:8000/users/signup
Header: 
  content-type: application/json
  email: clo@sparta.com

{
    "email": "clo@sparta.com",
    "name": "clo",
    "accessKey": "cugC5Rn2vzGEWUJhHAKw",
    "serviceId": "ncp:sms:kr:313324923877:clo",
    "secretKey": "z7KIKoY9QAtb1kGTlwWDBIigPfPWkLw9yALApZLv",
    "advertisementOpt": false
}

### login
Post http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "clo2@sparta.com"
}

### update User-info
Patch http://localhost:8000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTIwODk2NzAsImV4cCI6MTY5MjE3NjA3MH0.X5YJGZ12Uq1rmjLCCGTmbHvEREWpECOQvhZPaBwVy8U
Content-Type: application/json

{
    "hostnumber": ["010-3628-9823"]
}

### logout
POST http://localhost:8000/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTIwODk2NzAsImV4cCI6MTY5MjE3NjA3MH0.X5YJGZ12Uq1rmjLCCGTmbHvEREWpECOQvhZPaBwVy8U
Content-Type: application/json

### dafault message sending
Post http://localhost:8000/messages/default
Content-Type: application/json

{
    "hostnumber": "01036289823",
    "title": "Effic is the best!",
    "content": "test message입니다. \n안녕하세요 #{name}님! \n#{phone} 번호 맞으시죠? \n아래의 url을 눌러 마음에 드는 것이 있다면 속으로만 생각해주세요. \nhttps://www.google.com https://www.naver.com",
    "receiverList": [{"phone": "01036289823", "name": "clo"},{"phone": "01099287706", "name": "woo"}],
    "advertiseInfo": false,
    "urlList": ["https://www.google.com","https://www.naver.com"]
}

### dafault message result - shortio
### test용입니다 실제로 사용되지 않습니다.
Get http://localhost:8000/results/default/3
Content-Type: application/json


### dafault message result - ncp 
### test용입니다 실제로 사용되지 않습니다.
Get http://localhost:8000/results/default/ncp/42
Header: 
  content-type: application/json
  email: clo@sparta.com

### create payment
Post http://localhost:8000/payments
Header: 
  content-type: application/json
  email: clo@sparta.com

{
    "money": 1000
}

### result - messageId
Get http://localhost:8000/results/2
Content-Type: application/json


### abTest message sending
Post http://localhost:8000/messages/abtest
Content-Type: application/json

{
    "messageInfoList": [{"type": "A", "title": "Effic is the best!-A", "content": "A test message입니다. \n안녕하세요 #{name}님! \n#{phone} 번호 맞으시죠? \n아래의 url을 눌러 마음에 드는 것이 있다면 속으로만 생각해주세요. \nhttps://www.google.com https://www.naver.com", "advertiseInfo": false, "urlList": ["https://www.google.com","https://www.naver.com"]},{"type": "B", "title": "Effic is the best!-B", "content": "B test message입니다. \n메세지를 받은 #{name}님! \n현재 #{name}님의 등급은#{grade}입니다. \n더 많은 물품을 보시고 싶으시면 아래의 url을 눌러주세요. \nhttps://www.google.com https://www.daum.net", "advertiseInfo": false, "urlList": ["https://www.google.com","https://www.daum.net"]}],
    "urlForResult": "https://www.google.com",
    "hostnumber": "01036289823",
    "receiverList": [{"phone": "01036289823", "name": "clo", "grade": "A"},{"phone": "01036289823", "name": "clo2", "grade": "B"},{"phone": "01036289823", "name": "clo3", "grade": "A"},{"phone": "01036289823", "name": "clo4", "grade": "C"},{"phone": "01036289823", "name": "clo5", "grade": "B"},{"phone": "01036289823", "name": "clo6", "grade": "D"}]
}
