### Create User
POST http://localhost:8000/users/signup
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsb0BzcGFydGEuY29tIiwiaWF0IjoxNjk1NjI3ODk5LCJleHAiOjE2OTU3MTQyOTl9.YmP-aYte4C0P36wBwdRRX7nrTsnJ6wJNm9sS_ils8o8
Content-Type: application/json

{
    "email": "clo@sparta.com",
    "name": "clo",
    "accessKey": "dw1eiSLRQ6Nj2bAOlzsB",
    "serviceId": "ncp:sms:kr:260423710982:spartacodingclub",
    "secretKey": "x5zzaAzozM5h0k36cROO6LEuUMyRqP0di1eWXHJu",
    "hostnumber": ["15228016"],
    "advertiseNumber": ["08011111111"],
    "advertisementOpt": false
}

### login
Post http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "clo@sparta.com"
}

### update User-info
Patch http://localhost:8000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiY2xvM0BzcGFydGEuY29tIiwiaWF0IjoxNjkzMzg4NTk3LCJleHAiOjE2OTM0NzQ5OTd9.Gb7okqJIgwjQVd2MRmuUwle2h0jntllfzLMYp-gKOcQ
Content-Type: application/json

{
    "hostnumber": ["01036289827"],
    "advertiseNumber": ["0801111112"],
    "name": "clo2"
}

### logout
POST http://localhost:8000/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTIwODk2NzAsImV4cCI6MTY5MjE3NjA3MH0.X5YJGZ12Uq1rmjLCCGTmbHvEREWpECOQvhZPaBwVy8U
Content-Type: application/json

### dafault message sending
Post http://localhost:8000/messages/default
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTMzOTMwNjEsImV4cCI6MTY5MzQ3OTQ2MX0.ydgObk2ykaxW8cFb8QdOCk0utFaHxkn7Ciiprwfzji4
Content-Type: application/json

{
    "hostnumber": "15228016",
    "title": "Effic is the best!",
    "content": "test message입니다. \n안녕하세요 #{name}님! \n#{phone} 번호 맞으시죠? \n아래의 url을 눌러 마음에 드는 것이 있다면 속으로만 생각해주세요. \nhttps://www.google.com https://www.naver.com",
    "receiverList": [{"phone": "01036289823", "name": "clo"}],
    "advertiseInfo": false,
    "urlList": ["https://www.google.com","https://www.naver.com"]
}

### test message sending
Post http://localhost:8000/messages/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTIwODk2NzAsImV4cCI6MTY5MjE3NjA3MH0.X5YJGZ12Uq1rmjLCCGTmbHvEREWpECOQvhZPaBwVy8U
Content-Type: application/json

{
    "hostnumber": "15228016",
    "title": "Effic is the best!",
    "content": "test message입니다. \n안녕하세요 #{name}님! \n#{phone} 번호 맞으시죠? \n아래의 url을 눌러 마음에 드는 것이 있다면 속으로만 생각해주세요. \nhttps://www.google.com https://www.naver.com",
    "receiverList": [{"phone": "01036289823", "name": "clo"}],
    "advertiseInfo": false,
    "urlList": ["https://www.google.com","https://www.naver.com"]
}

### hostnumber check
Post http://localhost:8000/messages/checkhostnumber
Content-Type: application/json

{
    "hostnumber": "15228016",
    "accessKey":,
    "secretKey":,
    "serviceId":,
    "advertiseInfo": false,
}

### dafault message result - shortio
### test용입니다 실제로 사용되지 않습니다.
Get http://localhost:8000/results/default/6
Content-Type: application/json


### dafault message result - ncp 
### test용입니다 실제로 사용되지 않습니다.
Get http://localhost:8000/results/default/ncp/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ0MDUzNDEsImV4cCI6MTY5NDQ5MTc0MX0.EzZnKByWYN0jbb_mogFluYy3FjY_lvD2F0dXd1zsrws
Content-Type: application/json

### tly info
### test용입니다. 실제로 사용되지 않습니다.
Get http://localhost:8000/shorturl/tlyinfo


### create payment
Post http://localhost:8000/payments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsb0BzcGFydGEuY29tIiwiaWF0IjoxNjkzOTgxNTY4LCJleHAiOjE2OTQwNjc5Njh9.wtd6CLkethnPASO_aN5lJ1nz1rq6vxWS0A2y6K1gzdQ
Content-Type: application/json

{
    "money": 1000,
    "paymentMethod": "card"
}

### result - messageId
Get http://localhost:8000/results/6
Content-Type: application/json


### abTest message sending
Post http://localhost:8000/messages/abtest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTIwODk2NzAsImV4cCI6MTY5MjE3NjA3MH0.X5YJGZ12Uq1rmjLCCGTmbHvEREWpECOQvhZPaBwVy8U
Content-Type: application/json

{
    "messageInfoList": [{"type": "A", "title": "Effic is the best!-A", "content": "A test message입니다. \n안녕하세요 #{name}님! \n#{phone} 번호 맞으시죠? \n아래의 url을 눌러 마음에 드는 것이 있다면 속으로만 생각해주세요. \nhttps://www.google.com https://www.naver.com", "advertiseInfo": true, "urlList": ["https://www.google.com","https://www.naver.com"]},{"type": "B", "title": "Effic is the best!-B", "content": "B test message입니다. \n메세지를 받은 #{name}님! \n현재 #{name}님의 등급은#{grade}입니다. \n더 많은 물품을 보시고 싶으시면 아래의 url을 눌러주세요. \nhttps://www.google.com https://www.daum.net", "advertiseInfo": false, "urlList": ["https://www.google.com","https://www.daum.net"]}],
    "urlForResult": "https://www.google.com",
    "hostnumber": "15228016",
    "receiverList": [{"phone": "01036289823", "name": "clo", "grade": "A"},{"phone": "01936289823", "name": "clo2", "grade": "B"},{"phone": "01836289823", "name": "clo3", "grade": "A"},{"phone": "01736289823", "name": "clo4", "grade": "C"},{"phone": "01636289823", "name": "clo5", "grade": "B"},{"phone": "01536289823", "name": "clo6", "grade": "D"},{"phone": "01899989278", "name": "clo7", "grade": "B"},{"phone": "01899989279", "name": "clo8", "grade": "B"},{"phone": "01899989288", "name": "clo9", "grade": "B"},{"phone": "01899989458", "name": "clo10", "grade": "B"}]
}

### money - 사용 금액 내역 (userId)
Get http://localhost:8000/results/payment/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTMzNzcyNDMsImV4cCI6MTY5MzQ2MzY0M30._PYhQqklOQ24kA2aY5Bdo8Ro6pePYMQq3ENftSRRskM
Content-Type: application/json

### money - 충전 금액 내역 (userId)
Get http://localhost:8000/payments/me
Authorization:
Content-Type: application/json

### slack - 환불 메세지 보내기
Post http://localhost:8000/payments/refund
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTMyOTkyNjQsImV4cCI6MTY5MzM4NTY2NH0.IO67KL7OkKU0x4cy79jLdF_Qytdwp6sR-WEFNqFyX1w
Content-Type: application/json

{
  "refundMoney": 1000,
  "accountHolder": "승",
  "accountNumber": "1002-350-123456",
  "bankName": "우리은행",
  "contactNumber": "010-3628-9823"
}

### 마이페이지
Get http://localhost:8000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NjEyNTMsImV4cCI6MTY5NDc0NzY1M30.YX7YetIVtrok4smc52lLpw4m2mgqlMjv-r7ien6yEq0

# {
#   "userId": 1,
#   "email": "clo@sparta.com",
#   "name": "clo",
#   "hostnumber": [
#     "15228016"
#   ],
#   "advertisementOpt": false,
#   "advertiseNumber": [
#     "08011111111"
#   ],
#   "accessKey": "dw1eiSLRQ6Nj2bAOlzsB",
#   "serviceId": "ncp:sms:kr:260423710982:spartacodingclub",
#   "secretKey": "x5zzaAzozM5h0k36cROO6LEuUMyRqP0di1eWXHJu",
#   "bizServiceId": "ncp:kkobizmsg:kr:2604237:spartacodingclub",
#   "plusFriendIdList": [
#     {
#       "plusFriendId": "@스파르타코딩클럽",
#       "memo": "스파르타"
#     },
#     {
#       "plusFriendId": "@항해",
#       "memo": ""
#     }
#   ],
#   "point": 3000,
#   "money": 0
# }

### 주소록 생성
Post http://localhost:8000/phonebook
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg
Content-Type: application/json

{
    "title": "항해 초청 명단",
    "members": [{"name": "김민수", "number": "01099889782"}, {"name": "김영석", "number": "01099889781"}]
}

# {
#   "title": "스파르타 초청 명단",
#   "members": [
#     4,
#     2
#   ],
#   "createdAt": "2023-09-14T09:20:57.528Z",
#   "userId": 1,
#   "phonebookId": 3,
#   "updatedAt": "2023-09-14T09:20:57.533Z"
# }

### 주소록 멤버 수정
Patch http://localhost:8000/phonebook/members/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg
Content-Type: application/json

{
    "name": "김영철",
    "number": "01087654320"
}

# {
#   "contactId": 3,
#   "name": "김철희",
#   "number": "01099889786",
#   "userId": 1
# }

### 주소록 목록 조회
GET http://localhost:8000/phonebook/Allcontacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg

# [
#   {
#     "phonebookId": 1,
#     "title": "점심식사 초청 명단",
#     "membersAmount": 1,
#     "createdAt": "2023-09-14T08:14:35.553Z",
#     "updatedAt": "2023-09-14T09:11:01.268Z",
#     "userId": 1
#   },
#   {
#     "phonebookId": 3,
#     "title": "항해99 초청 명단",
#     "membersAmount": 1,
#     "createdAt": "2023-09-14T09:20:57.528Z",
#     "updatedAt": "2023-09-15T02:30:25.402Z",
#     "userId": 1
#   },
#   {
#     "phonebookId": 2,
#     "title": "정글 초청 명단",
#     "membersAmount": 2,
#     "createdAt": "2023-09-14T08:15:22.739Z",
#     "updatedAt": "2023-09-15T02:30:46.867Z",
#     "userId": 1
#   },
#   {
#     "phonebookId": 4,
#     "title": "에픽 초청 명단",
#     "membersAmount": 4,
#     "createdAt": "2023-09-15T02:19:03.011Z",
#     "updatedAt": "2023-09-15T03:24:48.852Z",
#     "userId": 1
#   }
# ]

### 주소록 멤버 조회
Get http://localhost:8000/phonebook/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg

# {
#   "phonebookId": 2,
#   "title": "정글 초청 명단",
#   "createdAt": "2023-09-14T08:15:22.739Z",
#   "updatedAt": "2023-09-15T02:30:46.867Z",
#   "userId": 1,
#   "memberInfoList": [
#     {
#       "contactId": 2,
#       "name": "김영희",
#       "number": "01087654321"
#     },
#     {
#       "contactId": 3,
#       "name": "김철희",
#       "number": "01099889786"
#     }
#   ]
# }

### 주소록 멤버 삭제
Delete http://localhost:8000/phonebook/3/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg

# {
#   "phonebookId": 1,
#   "title": "점심식사 초청 명단",
#   "members": [
#     1
#   ],
#   "createdAt": "2023-09-14T08:14:35.553Z",
#   "updatedAt": "2023-09-14T09:11:01.268Z",
#   "userId": 1
# }

### 주소록 title 수정
Patch http://localhost:8000/phonebook/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg
Content-Type: application/json

{
    "title": "정글 초청 명단"
}

# {
#   "phonebookId": 2,
#   "title": "정글 초청 명단",
#   "members": [
#     2,
#     3
#   ],
#   "createdAt": "2023-09-14T08:15:22.739Z",
#   "updatedAt": "2023-09-15T02:30:46.867Z",
#   "userId": 1
# }

### 주소록 멤버 추가
Post http://localhost:8000/phonebook/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg
Content-Type: application/json

{
    "addMembers": [{"name": "권용재", "number": "01099889783"}, {"name": "방민석", "number": "01099998887"}, {"name": "김영희", "number": "01087654321"}]
}

# {
#   "phonebookId": 4,
#   "title": "에픽 초청 명단",
#   "members": [
#     5,
#     2,
#     10,
#     11
#   ],
#   "createdAt": "2023-09-15T02:19:03.011Z",
#   "updatedAt": "2023-09-15T03:24:48.852Z",
#   "userId": 1
# }

### 주소록 삭제
DELETE http://localhost:8000/phonebook/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg

### 광고성 문자 수신자 필터링
Post http://localhost:8000/messages/filter
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg
Content-Type: application/json

{
    "receiverList": ["01799998888", "01999989889", "01899989278"],
    "day": 1
}

# {
#   "filteredReceivers": [
#     "01799998888",
#     "01999989889"
#   ]
# }

### 발신번호 수정
Patch http://localhost:8000/users/me/hostnumber
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg
Content-Type: application/json

{
    "hostnumberwithmemo": [{"hostnumber":"15228016","memo": "스파르타"}, {"hostnumber":"01036289823","memo": ""}, {"hostnumber":"01011111113","memo": "항해"}]
}

# [
#   {
#     "hostnumberDetailId": 1,
#     "hostnumber": "15228016",
#     "memo": "스파르타",
#     "userId": 1
#   },
#   {
#     "hostnumberDetailId": 2,
#     "hostnumber": "01036289823",
#     "memo": "",
#     "userId": 1
#   },
#   {
#     "hostnumberDetailId": 3,
#     "hostnumber": "01011111113",
#     "memo": "항해",
#     "userId": 1
#   }
# ]

### 발신번호와 메모 정보 가져오기
Get http://localhost:8000/users/hostnumberdetail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg

# [
#   {
#     "hostnumberDetailId": 16,
#     "hostnumber": "15228016",
#     "memo": "스파르타",
#     "userId": 1
#   },
#   {
#     "hostnumberDetailId": 17,
#     "hostnumber": "01036289823",
#     "memo": "",
#     "userId": 1
#   },
#   {
#     "hostnumberDetailId": 18,
#     "hostnumber": "01011111113",
#     "memo": "항해",
#     "userId": 1
#   }
# ]

### bizmessage serviceId 입력
Patch http://localhost:8000/users/me/bizserviceid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsb0BzcGFydGEuY29tIiwiaWF0IjoxNjk1NjI3ODk5LCJleHAiOjE2OTU3MTQyOTl9.YmP-aYte4C0P36wBwdRRX7nrTsnJ6wJNm9sS_ils8o8
Content-Type: application/json

{
    "bizServiceId": "ncp:kkobizmsg:kr:2604237:spartacodingclub"
}

# {
#   "userInfoNcpId": 1,
#   "accessKey": "dw1eiSLRQ6Nj2bAOlzsB",
#   "serviceId": "ncp:sms:kr:260423710982:spartacodingclub",
#   "bizServiceId": "ncp:kkobizmsg:kr:2604237:spartacodingclub",
#   "secretKey": "x5zzaAzozM5h0k36cROO6LEuUMyRqP0di1eWXHJu",
#   "advertiseNumber": [
#     "0801111112"
#   ],
#   "hostnumber": [
#     "15228016",
#     "01036289823",
#     "01011111113"
#   ],
#   "userId": 1
# }

### bizmessage plusFriendId와 메모 입력
PATCH http://localhost:8000/users/me/plusfriendid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg
Content-Type: application/json

{
    "plusFriendIdList": [{"plusFriendId":"@스파르타코딩클럽","memo": "스파르타"}, {"plusFriendId":"@항해","memo": ""}]
}

# {
#   "userInfoNcpId": 1,
#   "accessKey": "dw1eiSLRQ6Nj2bAOlzsB",
#   "serviceId": "ncp:sms:kr:260423710982:spartacodingclub",
#   "bizServiceId": "ncp:kkobizmsg:kr:2604237:spartacodingclub",
#   "secretKey": "x5zzaAzozM5h0k36cROO6LEuUMyRqP0di1eWXHJu",
#   "advertiseNumber": [
#     "08011111111"
#   ],
#   "hostnumber": [
#     "15228016"
#   ],
#   "plusFriendIdList": [
#     {
#       "plusFriendId": "@스파르타코딩클럽",
#       "memo": "스파르타"
#     },
#     {
#       "plusFriendId": "@항해",
#       "memo": ""
#     }
#   ],
#   "userId": 1
# }


### NCP에 이미지 업로드 
### 이 파일에서는 사용할 수 없습니다. 이미지 업로드가 가능한 postman이나 thunderclient를 사용해주세요.
### isWide값과, imageFile, plusFriendId를 form-data로 보내주세요.
### 예) isWide: false(type - string), imageFile: image.png, plusFriendId: @스파르타코딩클럽
Post http://localhost:8000/bizmessage/image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg

# {
#   "imageId": "8ae5c21c8ab116a0018ab5c4b02a0018",
#   "imageUrl": "https://mud-kage.kakao.com/dn/buUHWr/btsuOhFHl8v/Q4N6q9XAYyMjASzjRqb401/img_l.jpg",
#   "imageName": "image.png",
#   "isWide": false,
#   "createTime": "2023-09-21T12:24:40.874"
# }

### 친구톡 - 기본
### buttonInfo - WL : 웹링크(https://~~ or http://~~), AL : 앱링크()
### buttonInfo의 type이 WL일 경우 - buttonLink 사용
### buttonInfo의 type이 AL일 경우 - schemeIos, schemeAndroid 사용
Post http://localhost:8000/bizmessage/default
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTUyODM0MzksImV4cCI6MTY5NTM2OTgzOX0.1VgCXiTmwXFpHTAPnHirAS2Yi2Vr8txr4ngRxhNekMo
Content-Type: application/json

{
    "plusFriendId": "@스파르타코딩클럽",
    "bizMessageInfoList": {"content": "기본 친구톡 테스트 \nEffic을 무료로 사용해보세요!", "isAd": false, "urlList": []},
    "receiverList": [{"phone": "01036289823", "name": "clo"}, {"phone": "01848415676", "name": "clo2"}],
    "imageInfo": {"imageId": "8ae5c21e8ab7022c018abab5f34f000a", "imageLink": "https://app.effic.biz"},
    "buttonInfoList": [{"type": "WL", "name": "히히💕", "linkMobile" : "https://www.naver.com", "linkPc": "https://app.effic.biz"}, {"type": "WL", "name": "하하", "linkMobile" : "https://www.google.com", "linkPc": "https://app.effic.biz"}]
}

# {
#   "bizmessageId": 9,
#   "bizmessageGroupId": 9
# }

### 친구톡 ncp 결과조회 - 실제로 사용되지 않습니다.
Get http://localhost:8000/results/bizmessage/ncp/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTU2MDc4NzYsImV4cCI6MTY5NTY5NDI3Nn0.D3I7SWWuuYULbDvJm2NCczLPGRR3lbixO2sQrgS9Q60

### 친구톡 url 클릭 결과조회 - 실제로 사용되지 않습니다
Get http://localhost:8000/results/bizmessage/url/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTU2MDc4NzYsImV4cCI6MTY5NTY5NDI3Nn0.D3I7SWWuuYULbDvJm2NCczLPGRR3lbixO2sQrgS9Q60

# {
#   "contentArray": [],
#   "imageArray": [
#     {
#       "totalClicks": 0,
#       "humanClicks": 0,
#       "idString": "lnk_3xIn_WsTTXvmtxr9s2uTxTKwbN"
#     }
#   ],
#   "buttonArray": [
#     {
#       "pc": {
#         "totalClicks": 0,
#         "humanClicks": 0,
#         "idString": "lnk_3xIn_MrU1N8Y6PnJQZ1T95Pb12"
#       },
#       "mobile": {
#         "totalClicks": 0,
#         "humanClicks": 0,
#         "idString": "lnk_3xIn_Ijm5BMnFnnURvZMQAQsLn"
#       }
#     },
#     {
#       "pc": {
#         "totalClicks": 0,
#         "humanClicks": 0,
#         "idString": "lnk_3xIn_RdYJQAof5D6kaaI0RdM6P"
#       },
#       "mobile": {
#         "totalClicks": 0,
#         "humanClicks": 0,
#         "idString": "lnk_3xIn_hvNm3Kdb6hcIGZN58waGa"
#       }
#     }
#   ]
# }

### 친구톡 결과조회
Get http://localhost:8000/results/bizmessage/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTU2MDc4NzYsImV4cCI6MTY5NTY5NDI3Nn0.D3I7SWWuuYULbDvJm2NCczLPGRR3lbixO2sQrgS9Q60

# [
#   {
#     "bizmessage": 2,
#     "user": 1,
#     "urls": {
#       "content": [],
#       "image": [
#         {
#           "idString": "lnk_3xIn_C1kONiIRCE0Kt79Fd8cHZ",
#           "shortUrl": "https://effi.kr/YV9m4A",
#           "originalUrl": "https://app.effic.biz",
#           "humanclicks": 0,
#           "totalclicks": 0
#         }
#       ],
#       "button": [
#         {
#           "pc": {
#             "idString": "lnk_3xIn_4otZlSqdy1lE5Hzu98sUU",
#             "shortUrl": "https://effi.kr/PLwwqj",
#             "originalUrl": "https://app.effic.biz",
#             "humanclicks": 0,
#             "totalclicks": 0
#           }
#         },
#         {
#           "mobile": {
#             "idString": "lnk_3xIn_JEYdA2oCNuwq6XfImgz8h",
#             "shortUrl": "https://effi.kr/D8gedO",
#             "originalUrl": "https://www.naver.com",
#             "humanclicks": 0,
#             "totalclicks": 0
#           }
#         },
#         {
#           "pc": {
#             "idString": "lnk_3xIn_lyBZsGYkKPqP3cyJQjoYN",
#             "shortUrl": "https://effi.kr/v9nOsa",
#             "originalUrl": "https://app.effic.biz",
#             "humanclicks": 0,
#             "totalclicks": 0
#           }
#         },
#         {
#           "mobile": {
#             "idString": "lnk_3xIn_u611vivoxWEG1knRzCQtN",
#             "shortUrl": "https://effi.kr/BknjLW",
#             "originalUrl": "https://www.google.com",
#             "humanclicks": 0,
#             "totalclicks": 0
#           }
#         }
#       ]
#     },
#     "success": 1,
#     "reserved": 0,
#     "fail": 1,
#     "createdAt": "2023-09-27T08:56:15.073Z"
#   },
#   ...
# ]

### 친구톡 테스트 발송
Post http://localhost:8000/bizmessage/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTUyODM0MzksImV4cCI6MTY5NTM2OTgzOX0.1VgCXiTmwXFpHTAPnHirAS2Yi2Vr8txr4ngRxhNekMo
Content-Type: application/json

{
    "plusFriendId": "@스파르타코딩클럽",
    "bizMessageInfoList": {"content": "기본 친구톡 테스트 \nEffic을 무료로 사용해보세요!", "isAd": false, "urlList": []},
    "receiverList": [{"phone": "01036289823", "name": "clo"}, {"phone": "01848415676", "name": "clo2"}],
    "imageInfo": {"imageId": "8ae5c21e8ab7022c018abab5f34f000a", "imageLink": "https://app.effic.biz"},
    "buttonInfoList": [{"type": "WL", "name": "히히💕", "linkMobile" : "https://www.naver.com", "linkPc": "https://app.effic.biz"}, {"type": "WL", "name": "하하", "linkMobile" : "https://www.google.com", "linkPc": "https://app.effic.biz"}]
}

# success

### ab 친구톡 보내기
Post http://localhost:8000/bizmessage/abtest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTUyODM0MzksImV4cCI6MTY5NTM2OTgzOX0.1VgCXiTmwXFpHTAPnHirAS2Yi2Vr8txr4ngRxhNekMo
Content-Type: application/json

{
    "plusFriendId": "@스파르타코딩클럽",
    "receiverList": [{"phone": "01036289823", "name": "clo"}, {"phone": "01848415676", "name": "clo2"}],
    "messageInfoList": [{"type": "A", "bizMessageInfoList": {"content": "A 친구톡 테스트 \nEffic을 무료로 사용해보세요!", "isAd": false, "urlList": []}, "imageInfo": {"imageId": "8ae5c21e8ab7022c018abab5f34f000a", "imageLink": "https://app.effic.biz"}, "buttonInfoList": [{"type": "WL", "name": "히히💕", "buttonLink":"https://www.google.com"},{"type": "WL", "name": "하하", "buttonLink":"https://www.naver.com"}]}, {"type": "B", "bizMessageInfoList": {"content": "B 친구톡 테스트 \nEffic을 무료로 사용해보세요!", "isAd": false, "urlList": []}, "buttonInfoList": [{"type": "WL", "name": "하하", "buttonLink":"https://app.effic.biz"}]}],
}
