### Create User
POST http://localhost:8000/users/signup
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsb0BzcGFydGEuY29tIiwiaWF0IjoxNjk0NTk2ODgxLCJleHAiOjE2OTQ2ODMyODF9.Q2y91DtvtO-iXnBleP_ui9YF42rg7hv-1kntw0Dw38c
Content-Type: application/json

{
    "email": "clo@sparta.com",
    "name": "clo",
    "accessKey": "dw1eiSLRQ6Nj2bAOlzsB",
    "serviceId": "ncp:sms:kr:260423710982:spartacodingclub",
    "secretKey": "x5zzaAzozM5h0k36cROO6LEuUMyRqP0di1eWXHJu",
    "hostnumber": ["15228016"],
    "advertiseNumber": ["08011111111"],
    "advertisementOpt": false
}

### login
Post http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "clo@sparta.com"
}

### update User-info
Patch http://localhost:8000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiY2xvM0BzcGFydGEuY29tIiwiaWF0IjoxNjkzMzg4NTk3LCJleHAiOjE2OTM0NzQ5OTd9.Gb7okqJIgwjQVd2MRmuUwle2h0jntllfzLMYp-gKOcQ
Content-Type: application/json

{
    "hostnumber": ["01036289827"],
    "advertiseNumber": ["0801111112"],
    "name": "clo2"
}

### logout
POST http://localhost:8000/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTIwODk2NzAsImV4cCI6MTY5MjE3NjA3MH0.X5YJGZ12Uq1rmjLCCGTmbHvEREWpECOQvhZPaBwVy8U
Content-Type: application/json

### dafault message sending
Post http://localhost:8000/messages/default
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTMzOTMwNjEsImV4cCI6MTY5MzQ3OTQ2MX0.ydgObk2ykaxW8cFb8QdOCk0utFaHxkn7Ciiprwfzji4
Content-Type: application/json

{
    "hostnumber": "15228016",
    "title": "Effic is the best!",
    "content": "test message입니다. \n안녕하세요 #{name}님! \n#{phone} 번호 맞으시죠? \n아래의 url을 눌러 마음에 드는 것이 있다면 속으로만 생각해주세요. \nhttps://www.google.com https://www.naver.com",
    "receiverList": [{"phone": "01036289823", "name": "clo"}],
    "advertiseInfo": false,
    "urlList": ["https://www.google.com","https://www.naver.com"]
}

### test message sending
Post http://localhost:8000/messages/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTIwODk2NzAsImV4cCI6MTY5MjE3NjA3MH0.X5YJGZ12Uq1rmjLCCGTmbHvEREWpECOQvhZPaBwVy8U
Content-Type: application/json

{
    "hostnumber": "15228016",
    "title": "Effic is the best!",
    "content": "test message입니다. \n안녕하세요 #{name}님! \n#{phone} 번호 맞으시죠? \n아래의 url을 눌러 마음에 드는 것이 있다면 속으로만 생각해주세요. \nhttps://www.google.com https://www.naver.com",
    "receiverList": [{"phone": "01036289823", "name": "clo"}],
    "advertiseInfo": false,
    "urlList": ["https://www.google.com","https://www.naver.com"]
}

### hostnumber check
Post http://localhost:8000/messages/checkhostnumber
Content-Type: application/json

{
    "hostnumber": "15228016",
    "accessKey":,
    "secretKey":,
    "serviceId":,
    "advertiseInfo": false,
}

### dafault message result - shortio
### test용입니다 실제로 사용되지 않습니다.
Get http://localhost:8000/results/default/1
Content-Type: application/json


### dafault message result - ncp 
### test용입니다 실제로 사용되지 않습니다.
Get http://localhost:8000/results/default/ncp/23
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ0MDUzNDEsImV4cCI6MTY5NDQ5MTc0MX0.EzZnKByWYN0jbb_mogFluYy3FjY_lvD2F0dXd1zsrws
Content-Type: application/json

### tly info
### test용입니다. 실제로 사용되지 않습니다.
Get http://localhost:8000/results/tlyinfo/1


### create payment
Post http://localhost:8000/payments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsb0BzcGFydGEuY29tIiwiaWF0IjoxNjkzOTgxNTY4LCJleHAiOjE2OTQwNjc5Njh9.wtd6CLkethnPASO_aN5lJ1nz1rq6vxWS0A2y6K1gzdQ
Content-Type: application/json

{
    "money": 1000,
    "paymentMethod": "card"
}

### result - messageId
Get http://localhost:8000/results/1
Content-Type: application/json


### abTest message sending
Post http://localhost:8000/messages/abtest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTIwODk2NzAsImV4cCI6MTY5MjE3NjA3MH0.X5YJGZ12Uq1rmjLCCGTmbHvEREWpECOQvhZPaBwVy8U
Content-Type: application/json

{
    "messageInfoList": [{"type": "A", "title": "Effic is the best!-A", "content": "A test message입니다. \n안녕하세요 #{name}님! \n#{phone} 번호 맞으시죠? \n아래의 url을 눌러 마음에 드는 것이 있다면 속으로만 생각해주세요. \nhttps://www.google.com https://www.naver.com", "advertiseInfo": false, "urlList": ["https://www.google.com","https://www.naver.com"]},{"type": "B", "title": "Effic is the best!-B", "content": "B test message입니다. \n메세지를 받은 #{name}님! \n현재 #{name}님의 등급은#{grade}입니다. \n더 많은 물품을 보시고 싶으시면 아래의 url을 눌러주세요. \nhttps://www.google.com https://www.daum.net", "advertiseInfo": false, "urlList": ["https://www.google.com","https://www.daum.net"]}],
    "urlForResult": "https://www.google.com",
    "hostnumber": "15228016",
    "receiverList": [{"phone": "01036289823", "name": "clo", "grade": "A"},{"phone": "01936289823", "name": "clo2", "grade": "B"},{"phone": "01836289823", "name": "clo3", "grade": "A"},{"phone": "01736289823", "name": "clo4", "grade": "C"},{"phone": "01636289823", "name": "clo5", "grade": "B"},{"phone": "01536289823", "name": "clo6", "grade": "D"},{"phone": "01899989278", "name": "clo7", "grade": "B"},{"phone": "01899989279", "name": "clo8", "grade": "B"},{"phone": "01899989288", "name": "clo9", "grade": "B"},{"phone": "01899989458", "name": "clo10", "grade": "B"}]
}

### money - 사용 금액 내역 (userId)
Get http://localhost:8000/results/payment/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTMzNzcyNDMsImV4cCI6MTY5MzQ2MzY0M30._PYhQqklOQ24kA2aY5Bdo8Ro6pePYMQq3ENftSRRskM
Content-Type: application/json

### money - 충전 금액 내역 (userId)
Get http://localhost:8000/payments/me
Authorization:
Content-Type: application/json

### slack - 환불 메세지 보내기
Post http://localhost:8000/payments/refund
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTMyOTkyNjQsImV4cCI6MTY5MzM4NTY2NH0.IO67KL7OkKU0x4cy79jLdF_Qytdwp6sR-WEFNqFyX1w
Content-Type: application/json

{
  "refundMoney": 1000,
  "accountHolder": "승",
  "accountNumber": "1002-350-123456",
  "bankName": "우리은행",
  "contactNumber": "010-3628-9823"
}

### 마이페이지
Get http://localhost:8000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NjEyNTMsImV4cCI6MTY5NDc0NzY1M30.YX7YetIVtrok4smc52lLpw4m2mgqlMjv-r7ien6yEq0

### 주소록 생성
Post http://localhost:8000/phonebook
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg
Content-Type: application/json

{
    "title": "점심 초청 명단",
    "members": [{"name": "권용재", "number": "01099889783"}, {"name": "김영희", "number": "01087654321"}]
}

# {
#   "title": "스파르타 초청 명단",
#   "members": [
#     4,
#     2
#   ],
#   "createdAt": "2023-09-14T09:20:57.528Z",
#   "userId": 1,
#   "phonebookId": 3,
#   "updatedAt": "2023-09-14T09:20:57.533Z"
# }

### 주소록 멤버 수정
Patch http://localhost:8000/phonebook/members/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg
Content-Type: application/json

{
    "name": "김영철",
    "number": "01087654320"
}

# {
#   "contactId": 3,
#   "name": "김철희",
#   "number": "01099889786",
#   "userId": 1
# }

### 주소록 목록 조회
GET http://localhost:8000/phonebook/Allcontacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg

# [
#   {
#     "phonebookId": 1,
#     "title": "점심식사 초청 명단",
#     "membersAmount": 1,
#     "createdAt": "2023-09-14T08:14:35.553Z",
#     "updatedAt": "2023-09-14T09:11:01.268Z",
#     "userId": 1
#   },
#   {
#     "phonebookId": 3,
#     "title": "항해99 초청 명단",
#     "membersAmount": 1,
#     "createdAt": "2023-09-14T09:20:57.528Z",
#     "updatedAt": "2023-09-15T02:30:25.402Z",
#     "userId": 1
#   },
#   {
#     "phonebookId": 2,
#     "title": "정글 초청 명단",
#     "membersAmount": 2,
#     "createdAt": "2023-09-14T08:15:22.739Z",
#     "updatedAt": "2023-09-15T02:30:46.867Z",
#     "userId": 1
#   },
#   {
#     "phonebookId": 4,
#     "title": "에픽 초청 명단",
#     "membersAmount": 4,
#     "createdAt": "2023-09-15T02:19:03.011Z",
#     "updatedAt": "2023-09-15T03:24:48.852Z",
#     "userId": 1
#   }
# ]

### 주소록 멤버 조회
Get http://localhost:8000/phonebook/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg

# {
#   "phonebookId": 2,
#   "title": "정글 초청 명단",
#   "createdAt": "2023-09-14T08:15:22.739Z",
#   "updatedAt": "2023-09-15T02:30:46.867Z",
#   "userId": 1,
#   "memberInfoList": [
#     {
#       "contactId": 2,
#       "name": "김영희",
#       "number": "01087654321"
#     },
#     {
#       "contactId": 3,
#       "name": "김철희",
#       "number": "01099889786"
#     }
#   ]
# }


### 주소록 멤버 삭제
Delete http://localhost:8000/phonebook/3/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg

# {
#   "phonebookId": 1,
#   "title": "점심식사 초청 명단",
#   "members": [
#     1
#   ],
#   "createdAt": "2023-09-14T08:14:35.553Z",
#   "updatedAt": "2023-09-14T09:11:01.268Z",
#   "userId": 1
# }

### 주소록 title 수정
Patch http://localhost:8000/phonebook/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg
Content-Type: application/json

{
    "title": "정글 초청 명단"
}

# {
#   "phonebookId": 2,
#   "title": "정글 초청 명단",
#   "members": [
#     2,
#     3
#   ],
#   "createdAt": "2023-09-14T08:15:22.739Z",
#   "updatedAt": "2023-09-15T02:30:46.867Z",
#   "userId": 1
# }

### 주소록 멤버 추가
Post http://localhost:8000/phonebook/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg
Content-Type: application/json

{
    "addMembers": [{"name": "권용재", "number": "01099889783"}, {"name": "방민석", "number": "01099998887"}, {"name": "김영희", "number": "01087654321"}]
}

# {
#   "phonebookId": 4,
#   "title": "에픽 초청 명단",
#   "members": [
#     5,
#     2,
#     10,
#     11
#   ],
#   "createdAt": "2023-09-15T02:19:03.011Z",
#   "updatedAt": "2023-09-15T03:24:48.852Z",
#   "userId": 1
# }

### 주소록 삭제
DELETE http://localhost:8000/phonebook/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg

### 3일 이내 수신자 필터링
Post http://localhost:8000/messages/filter
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2xvQHNwYXJ0YS5jb20iLCJpYXQiOjE2OTQ2NzkyMDEsImV4cCI6MTY5NDc2NTYwMX0.UY9eeBrGyqHdAy6WCf1UyM0ro1QfQ-a9wqykaiY4MRg
Content-Type: application/json

{
    "receiverList": ["01799998888", "01999989889", "01899989278"]
}

# {
#   "filterReceivers": [
#     "01799998888",
#     "01999989889"
#   ]
# }